version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Mentory
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1g

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  keyvault:
    image: nagyesta/lowkey-vault:7.1.9-ubi10-minimal
    container_name: azure-keyvault
    ports:
      - "8443:8443"
    environment:
      # Expõe os dados sensíveis (necessário para o simulador funcionar em dev)
      - LOWKEY_VAULT_SENSITIVE_DATA_EXPOSED=true
      # arquivo fisico
      - LOWKEY_VAULT_DB_FILE=/app/data/lowkey-vault.db
    volumes:
      # Persiste os segredos na pasta local 
      - ~/lowkey_data:/app/data

volumes:
  postgres_data:
  pgadmin_data:  
