apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotline-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotline-webapi
  template:
    metadata:
      labels:
        app: hotline-webapi
    spec:
      containers:
      - name: hotline-webapi
        image: hotline-webapi:latest
        ports:
        - containerPort: 5002
        env:
        - name: DB_CONNECTION
          value: "Host=host.k3d.internal;Port=5432;Database=Mentory;Username=postgres;Password=postgres" 
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
