# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: hotline-frontend
spec:
  selector:
    app: hotline-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80      
  type: ClusterIP
  